In [4]:
import numpy as np
arr = np.array([[4,5,6],[8,9,11]])
res = arr * 3
print(res)


[[12 15 18]
 [24 27 33]]


In [30]:
array = np.array([[1,2,3,4],[3.5,5,6,7.9],[7,6,3,1]])
array1 = array[:2, ::3]
print(array1)

[[1.  4. ]
 [3.5 7.9]]


In [14]:
x = np.array([[2,3,4],[5,6,7]])
x.shape
y= np.array([[12,23,33],[4,9,10]])
sum = x+
print(x + y)


[[14 26 37]
 [ 9 15 17]]


In [15]:
sqr = np.sqrt(sum)
print(sqr)

[[3.74165739 5.09901951 6.08276253]
 [3.         3.87298335 4.12310563]]


In [17]:
print(x.T)

[[2 5]
 [3 6]
 [4 7]]


In [36]:
num = np.array([
                [1,2,3,4,5,6,7,8,9],
                [11,22,33,44,55,66,77,88,99],
                [12,34,23,45,56,32,14,65,78],
                [23,24,56,87,98,12,11,22,33],
                [23,43,65,87,98,10,21,45,51],
                [88,77,66,65,4,98,123,432,123]
               ])
num2 = num[2: , ::3]
print(num2)

[[ 12  45  14]
 [ 23  87  11]
 [ 23  87  21]
 [ 88  65 123]]


In [56]:
num.flatten()[:15].reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 22, 33],
       [44, 55, 66]])